# Settings
title:               CyberSecurity.org
description:
url:                 https://www.cybersecurity.org
baseurl:
brandedurl:          https://forms.cybersecurity.org
email:               contact+cybersecurityorg@highereducation.com
markdown:            kramdown
layouts_dir:         html/layouts
includes_dir:        html/includes
plugins_dir:         plugins
collections_dir:     # implement on Forestry.io changelog update: _collections
image_base:          assets/media
permalink:           :path/
publisher:           businessanalytics.com # CyberSecurity.org needs to be added to Platform Publishers
logo:                /assets/img/logo.png


# Collections
collections:
  pages:
    permalink:        :path/
    output:           true
  utilities:
    permalink:        :path
    output:           true
  examples:
    output:           true


# Defaults
defaults:
  - scope:
      path:           ""
    values:
      author:         "Staff Writers"
      featured_image:
      layout:         "default"
  - scope:
      path:           "_pages/index.html"
    values:
      permalink:      :path
  - scope:
      path:           "admin/**"
    values:
      sitemap:        false


# Widget
widget:
  ssr:               https://platform.highereducation.com/widgets.html?widget=ssr-qdf&backgroundColor=%23003652&cta=SEARCH%20SCHOOLS&ctaColor=%23FFCA00&height=325&title=FIND%20A%20DEGREE&titleColor=%23001F30


# Webmaster
webmaster:
  gtm: GTM-WBJKJ95
  google_analytics:
  google_verification:
  bing_verification:


# Algolia
algolia:
  api_id:            QT4LTISCL1
  api_key:           9169c7a55535b7c9c9660f115b9d7db1
  rankings:          bacom_rankings # used as example, will remove on deployment
  rankings_items:    bacom_rankings_items # used as example, will remove on deployment
  scholarships:      he_scholarships_v2.0
  ipeds:             he_ipeds


# Cloudinary
cloudinary:
  url:               https://res.cloudinary.com/highereducation/image/upload
  markup:            default
  breakpoints:       768|1024|1400
  quality:           auto:good
  format:            auto
  flag:              lossy
  crop:              fill


# Output Directory ~ Excludes, Includes, and Keep on Jekyll builds.
exclude:             [assets, html, plugins, pull_request_template.md, README.md, Gemfile, Gemfile.lock, package.json, node_modules, gulpfile.js, yarn.lock, .jshintrc, package-lock.json, netlify.toml]
include:             [_redirects, _headers]
keep_files:          [assets]


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-menus
